Repository myriadsocial/myriad-node, pull requests merged in 2022-04, with the labels that each got.

#98 Implement Tipping pallet
  Cargo.lock
  Cargo.toml
  docs/Functions.md
  node/src/chain_spec.rs
  pallets/currency/README.md
  pallets/currency/src/benchmarking.rs
  pallets/currency/src/lib.rs
  pallets/currency/src/mock.rs
  pallets/currency/src/tests.rs
  pallets/currency/src/weights.rs
  pallets/escrow/README.md
  pallets/escrow/src/benchmarking.rs
  pallets/escrow/src/lib.rs
  pallets/escrow/src/mock.rs
  pallets/escrow/src/tests.rs
  pallets/escrow/src/weights.rs
  pallets/platform/Cargo.toml
  pallets/platform/README.md
  pallets/platform/src/benchmarking.rs
  pallets/platform/src/lib.rs
  pallets/platform/src/tests.rs
  pallets/platform/src/weights.rs
  pallets/server/README.md
  pallets/server/src/benchmarking.rs
  pallets/server/src/interface.rs
  pallets/server/src/lib.rs
  pallets/server/src/tests.rs
  pallets/server/src/weights.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/README.md
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/benchmarking/src/mock.rs
  pallets/tipping/src/interface.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/tests.rs
  pallets/tipping/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Improvement

#102 Benchmarking and bumping spec_version to 105
  .github/workflows/deployer.yml
  pallets/server/src/weights.rs
  pallets/tipping/src/weights.rs
  runtime/src/lib.rs
Labels: Feature, CI

#103 Added new function
  pallets/server/src/benchmarking.rs
  pallets/server/src/lib.rs
  pallets/server/src/weights.rs
Labels: Improvement

#104 benchmarking
  pallets/server/src/weights.rs
Labels: enhancement

#93 Upgraded to polkadot v0.9.13
  .editorconfig
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/server/Cargo.toml
  pallets/server/src/interface.rs
  pallets/server/src/lib.rs
  pallets/server/src/tests.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/tests.rs
  runtime/Cargo.toml
  runtime/build.rs
  runtime/src/lib.rs
Labels: Feature

#105 chore: bump verison
  .maintain/benchmark.sh
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#108 Change server id from hash to string
  pallets/server/src/benchmarking.rs
  pallets/server/src/interface.rs
  pallets/server/src/lib.rs
  pallets/server/src/tests.rs
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/tests.rs
Labels: Improvement

#109 Bump version to 2.0.1
  .editorconfig
  .rustfmt.toml
  Cargo.lock
  node/Cargo.toml
  pallets/server/Cargo.toml
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#110 feat: updated to octopus v0.9.13
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/server/Cargo.toml
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#111 chore: bump version to 2.1.0
  Cargo.lock
  node/Cargo.toml
  pallets/server/Cargo.toml
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#112 improve tester add retag docker image condition
  .github/workflows/builder.yml
  .github/workflows/tester.yml
Labels: CI
