Repository myriadsocial/myriad-node, pull requests merged in 2022-02, with the labels that each got.

#94 Updated octopus pallets v0.9.12
  .github/workflows/builder.yml
  .github/workflows/tester.yml
  Cargo.lock
  node/src/chain_spec.rs
  runtime/src/lib.rs
Labels: Improvement

#95 Upload wasm file to discord
  .github/workflows/builder.yml
Labels: CI

#96 Update octopus pallets to latest v0.9.12
  Cargo.lock
  runtime/src/lib.rs
Labels: Feature
