Repository myriadsocial/myriad-node, pull requests merged in 2022-06, with the labels that each got.

#121 Implement offchain worker when connecting account
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/src/function.rs
  pallets/tipping/src/functions/api_call.rs
  pallets/tipping/src/functions/helper.rs
  pallets/tipping/src/functions/mod.rs
  pallets/tipping/src/functions/tips_balance.rs
  pallets/tipping/src/functions/unsigned_call.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/interface.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/types.rs
  pallets/tipping/src/types/api_response.rs
  pallets/tipping/src/types/mod.rs
  pallets/tipping/src/types/payload.rs
  pallets/tipping/src/types/tips_balance.rs
Labels: Improvement

#122 CI: improve deployment
  .github/workflows/deployer.yml
Labels: CI

#124 Added log
  pallets/tipping/src/functions/helper.rs
  pallets/tipping/src/lib.rs
Labels: Improvement

#125 Fixed verify social media
  pallets/tipping/src/functions/api_call.rs
  pallets/tipping/src/functions/helper.rs
  pallets/tipping/src/functions/unsigned_call.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/types/api_response.rs
  pallets/tipping/src/types/payload.rs
Labels: Improvement

#126 Fixed offchain worker when connect account
  pallets/tipping/src/functions/api_call.rs
  pallets/tipping/src/functions/helper.rs
  pallets/tipping/src/functions/unsigned_call.rs
Labels: Improvement

#127 ci: remove unused env
  .github/workflows/deployer.yml
Labels: CI

#128 feat: bump octopus pallet
  Cargo.lock
Labels: Feature

#129 chore: bump version to 2.1.2
  Cargo.lock
  node/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#130 ci: add sleuth webhook
  .github/workflows/deployer.yml
Labels: CI
