Repository myriadsocial/myriad-node, pull requests merged in 2022-07, with the labels that each got.

#131 ci: improve ci-cd
  .github/pull_request_template.md
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#132 style: code formatting
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
Labels: CI

#134 feat: batch claim reference method in substrate
  Cargo.lock
  node/Cargo.toml
  pallets/server/Cargo.toml
  pallets/server/src/lib.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/src/functions/tips_balance.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/interface.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/tests.rs
  pallets/tipping/src/types/tips_balance.rs
  pallets/tipping/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#135 feat: sendTip and claimTips with octopusAssets
  Cargo.lock
  node/Cargo.toml
  pallets/server/Cargo.toml
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/benchmarking/src/mock.rs
  pallets/tipping/src/crypto.rs
  pallets/tipping/src/functions.rs
  pallets/tipping/src/functions/api_call.rs
  pallets/tipping/src/functions/helper.rs
  pallets/tipping/src/functions/mod.rs
  pallets/tipping/src/functions/tips_balance.rs
  pallets/tipping/src/functions/unsigned_call.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/interface.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/tests.rs
  pallets/tipping/src/types.rs
  pallets/tipping/src/types/api_response.rs
  pallets/tipping/src/types/mod.rs
  pallets/tipping/src/types/payload.rs
  pallets/tipping/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature, Improvement

#137 feat: updated to polkadot 0.9.18 based
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/server/Cargo.toml
  pallets/server/src/lib.rs
  pallets/server/src/mock.rs
  pallets/server/src/tests.rs
  pallets/server/src/types.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/benchmarking/src/mock.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/types.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#139 feat: update to polkadot v0.9.18
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/server/Cargo.toml
  pallets/server/src/lib.rs
  pallets/server/src/mock.rs
  pallets/server/src/tests.rs
  pallets/server/src/types.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/benchmarking/Cargo.toml
  pallets/tipping/benchmarking/src/lib.rs
  pallets/tipping/benchmarking/src/mock.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/types.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature
