Repository myriadsocial/myriad-node, pull requests merged in 2023-01, with the labels that each got.

#149 feat: implement staking server
  Cargo.lock
  pallets/server/Cargo.toml
  pallets/server/src/benchmarking.rs
  pallets/server/src/functions.rs
  pallets/server/src/impl_server.rs
  pallets/server/src/interface.rs
  pallets/server/src/lib.rs
  pallets/server/src/migrations.rs
  pallets/server/src/mock.rs
  pallets/server/src/tests.rs
  pallets/server/src/types.rs
  pallets/server/src/weights.rs
  pallets/tipping/src/lib.rs
  runtime/src/lib.rs
Labels: Feature

#150 feat: update node to polkadot 0.9.30
  .github/workflows/builder.yml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .maintain/docker/injected-binnary.Dockerfile
  .maintain/pallet-weight-template.hbs
  Cargo.lock
  node/Cargo.toml
  node/src/benchmarking.rs
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/main.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/server/Cargo.toml
  pallets/server/src/functions.rs
  pallets/server/src/lib.rs
  pallets/server/src/migrations.rs
  pallets/server/src/mock.rs
  pallets/server/src/tests.rs
  pallets/server/src/weights.rs
  pallets/tipping/Cargo.toml
  pallets/tipping/src/functions.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/migrations.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/tests.rs
  pallets/tipping/src/weights.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Feature

#151 fix: handle deleted server when staked amount zero
  Cargo.lock
  node/src/command.rs
  pallets/server/src/benchmarking.rs
  pallets/server/src/functions.rs
  pallets/server/src/impl_server.rs
  pallets/server/src/interface.rs
  pallets/server/src/lib.rs
  pallets/server/src/migrations.rs
  pallets/server/src/tests.rs
  pallets/server/src/types.rs
  pallets/server/src/weights.rs
  pallets/tipping/src/benchmarking.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: Improvement

#152 feat: added new methods on tipping pallet
  pallets/tipping/src/benchmarking.rs
  pallets/tipping/src/functions.rs
  pallets/tipping/src/impl_tipping.rs
  pallets/tipping/src/interface.rs
  pallets/tipping/src/lib.rs
  pallets/tipping/src/migrations.rs
  pallets/tipping/src/mock.rs
  pallets/tipping/src/tests.rs
  pallets/tipping/src/types.rs
  pallets/tipping/src/weights.rs
  runtime/src/lib.rs
Labels: Improvement

#154 fix: octopus migration
  runtime/src/lib.rs
Labels: Fix
